-- Swiggy Food Delivery Analysis

USE swiggy_db;

-- Q1. How many total orders were placed?
SELECT COUNT(*) AS Total_orders
FROM orders;

-- Q2. What is the total revenue generated?
SELECT SUM(total_amount) AS Total_revenue
FROM orders;

-- Q3. What is the average order value?
SELECT AVG(total_amount) AS Avg_order_value
FROM orders;

-- Q4. How many unique customers placed orders?
SELECT COUNT(DISTINCT customer_id) AS Unique_customers
FROM orders;

-- Q5. How many orders were Completed vs Not Fulfilled?
SELECT order_status, COUNT(*) AS Total_orders
FROM Orders
GROUP BY order_status;

-- Q6. Which customers placed more than one order?
SELECT customer_id, COUNT(*) AS Total_orders
FROM orders
GROUP BY customer_id
HAVING Total_orders > 1
ORDER BY Total_orders DESC;

-- Q7. Which customer placed the most orders?
SELECT customers.customer_name, COUNT(orders.customer_id) AS Total_orders
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_name
ORDER BY Total_orders DESC
LIMIT 1;

-- Q8. Which customer has spent the most money?
SELECT customers.customer_name, SUM(orders.total_amount) AS Total_spending
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_name
ORDER BY Total_spending DESC
LIMIT 1;

-- Q9. Which restaurant generated the highest revenue?
SELECT restaurants.restaurant_name, SUM(orders.total_amount) AS Total_revenue
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_name
ORDER BY Total_revenue DESC
LIMIT 1;

-- Q10. How many orders did each restaurant receive?
SELECT restaurants.restaurant_name, COUNT(orders.restaurant_id) AS Total_orders
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_name 
ORDER BY Total_orders DESC;

-- Q11. What is the total revenue generated by each city?
SELECT restaurants.city, SUM(orders.total_amount) AS Total_revenue
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.city
ORDER BY Total_revenue DESC;

-- Q12. Which city has the highest number of orders?
SELECT restaurants.city, COUNT(orders.restaurant_id) AS Total_orders
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.city
ORDER BY Total_orders DESC;

-- Q13. What is the average order value for each city?
SELECT restaurants.city, AVG(orders.total_amount) AS Avg_order_value
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.city
ORDER BY Avg_order_value DESC;

-- Q14. Which restaurant has the highest average order value?
SELECT restaurants.restaurant_name, AVG(orders.total_amount) AS Avg_order_value
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_name
ORDER BY Avg_order_value DESC
LIMIT 1;

-- Q15. What is the total revenue generated by each restaurant?
SELECT restaurants.restaurant_name, SUM(orders.total_amount) AS Total_revenue
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_name
ORDER BY Total_revenue DESC;

-- Q16. How many orders are in each delivery status?
SELECT delivery_status, COUNT(*) AS Total_deliveries
FROM deliveries
GROUP BY delivery_status
ORDER BY Total_deliveries DESC;

-- 17. How many orders do not have a delivery record?
SELECT COUNT(*) AS Orders_without_delivery
FROM orders
LEFT JOIN deliveries
ON orders.order_id = deliveries.order_id
WHERE deliveries.order_id IS NULL;

-- 18. Which rider completed the most deliveries?
SELECT riders.rider_name, COUNT(deliveries.rider_id) AS Total_deliveries
FROM deliveries
INNER JOIN riders
ON deliveries.rider_id = riders.rider_id
WHERE deliveries.delivery_status = 'Delivered'
GROUP BY deliveries.rider_id, riders.rider_name
ORDER BY Total_deliveries DESC
LIMIT 1;

-- Q19. Which restaurants have an average order value greater than ₹500?
SELECT restaurants.restaurant_name, AVG(orders.total_amount) AS Avg_Order_Value
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_id, restaurants.restaurant_name
HAVING AVG(orders.total_amount) > 300
ORDER BY Avg_Order_Value DESC;

-- Q20. Which customers have never placed an order?
SELECT customers.customer_id, customers.customer_name
FROM customers
LEFT JOIN orders
ON customers.customer_id = orders.customer_id
WHERE orders.customer_id IS NULL;
  
-- Q21. Which restaurants have the highest number of unfulfilled orders?  
SELECT restaurants.restaurant_name, COUNT(*) AS Unfulfilled_orders
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
WHERE orders.order_status = 'Not Fulfilled'
GROUP BY restaurants.restaurant_id, restaurants.restaurant_name
ORDER BY Unfulfilled_orders DESC;

-- Q22. What are the top 10 most ordered dishes/items?
SELECT order_item, COUNT(*) AS Total_orders
FROM orders
GROUP BY order_item
ORDER BY Total_orders DESC
LIMIT 10;

-- Q23. What are the most popular dishes/items in each city?
SELECT restaurants.city, orders.order_item, COUNT(*) AS Total_orders
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.city, orders.order_item
ORDER BY restaurants.city, Total_orders DESC;

-- Q24. What are the most popular order time slots?
SELECT
CASE WHEN order_time >= '06:00:00' AND order_time < '12:00:00' THEN 'Morning'
WHEN order_time >= '12:00:00' AND order_time < '17:00:00' THEN 'Afternoon'
WHEN order_time >= '17:00:00' AND order_time < '21:00:00' THEN 'Evening'
ELSE 'Night'
END AS Time_slot,
COUNT(*) AS Total_orders
FROM orders
GROUP BY Time_slot
ORDER BY Total_orders DESC;

-- Q25. Rank restaurants by total revenue.
SELECT restaurants.restaurant_name, SUM(orders.total_amount) AS Total_revenue,
RANK() OVER (ORDER BY SUM(orders.total_amount) DESC) AS Restaurant_rank
FROM orders
INNER JOIN restaurants
ON orders.restaurant_id = restaurants.restaurant_id
GROUP BY restaurants.restaurant_id, restaurants.restaurant_name
ORDER BY Restaurant_rank;

-- Q26. Categorize customers based on total spending.
SELECT customers.customer_name, SUM(orders.total_amount) AS Total_spending,
CASE WHEN SUM(orders.total_amount) >= 200000 THEN 'Gold'
WHEN SUM(orders.total_amount) >= 100000 THEN 'Silver'
ELSE 'Normal'
END AS Customer_category
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, customers.customer_name
ORDER BY Total_spending DESC;

-- Q27. What are the monthly total orders and revenue?
SELECT DATE_FORMAT(order_date, '%Y-%m') AS Order_month, COUNT(*) AS Total_orders, SUM(total_amount) AS Total_revenue
FROM orders
GROUP BY Order_month
ORDER BY Order_month;

-- Q28. What is the estimated monthly earning of each rider?
SELECT riders.rider_name, DATE_FORMAT(orders.order_date, '%Y-%m') AS Order_month, (SUM(orders.total_amount) * 0.08) AS Estimated_earning
FROM deliveries
INNER JOIN riders
ON deliveries.rider_id = riders.rider_id
INNER JOIN orders 
ON deliveries.order_id = orders.order_id
WHERE deliveries.delivery_status = 'Delivered'
GROUP BY riders.rider_id, riders.rider_name, Order_month
ORDER BY Order_month, Estimated_earning DESC;

-- Q29. Which customers contribute the most revenue?
SELECT customers.customer_name, SUM(orders.total_amount) AS Total_revenue
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id, customers.customer_name
ORDER BY Total_revenue DESC;+






